// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoipDIU199uL2Vj3BSEWNEHpSXj9iBoC0',
    appId: '1:952319264508:web:6b76055f51cdbc1418b979',
    messagingSenderId: '952319264508',
    projectId: 'ecommerce-app-8cd21',
    authDomain: 'ecommerce-app-8cd21.firebaseapp.com',
    storageBucket: 'ecommerce-app-8cd21.firebasestorage.app',
    measurementId: 'G-Y6ZWN06TMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXs7CeTl9dae4WumrGsbYjJHAa15nQU5E',
    appId: '1:952319264508:android:384177b25a82cbdd18b979',
    messagingSenderId: '952319264508',
    projectId: 'ecommerce-app-8cd21',
    storageBucket: 'ecommerce-app-8cd21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASKmqzV0mbgmFCxm-baJ4r6JpiJHVTJLo',
    appId: '1:952319264508:ios:ccb50844c6f437cd18b979',
    messagingSenderId: '952319264508',
    projectId: 'ecommerce-app-8cd21',
    storageBucket: 'ecommerce-app-8cd21.firebasestorage.app',
    iosBundleId: 'com.example.adminPannel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASKmqzV0mbgmFCxm-baJ4r6JpiJHVTJLo',
    appId: '1:952319264508:ios:ccb50844c6f437cd18b979',
    messagingSenderId: '952319264508',
    projectId: 'ecommerce-app-8cd21',
    storageBucket: 'ecommerce-app-8cd21.firebasestorage.app',
    iosBundleId: 'com.example.adminPannel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoipDIU199uL2Vj3BSEWNEHpSXj9iBoC0',
    appId: '1:952319264508:web:96c47aa5464b1eab18b979',
    messagingSenderId: '952319264508',
    projectId: 'ecommerce-app-8cd21',
    authDomain: 'ecommerce-app-8cd21.firebaseapp.com',
    storageBucket: 'ecommerce-app-8cd21.firebasestorage.app',
    measurementId: 'G-5TYCPPSYCJ',
  );
}
